spring:
  profiles:
    active: dev

---
#开发环境配置
spring:
  profiles: master
  application:
    name: microservicecloud-config-atguigu-dev



---
#测试环境配置
spring:
  profiles: test
  application:
    name: microservicecloud-config-atguigu-test



          
          
          
          
